### ISSUE TITLE
Could not pass event PlayerQuitEvent to ClientDetector v2.4.8

### ISSUE THREAD

**Issue by sphings79** [Sportkanone123/ClientDetector#10]
**General Information**
Server version:  This server is running Paper version git-Paper-250 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a5be178)
You are running the latest version
Server software: Paper
Client version:  1.18.1 / 1.17.1
Client software: .GD Launcher
Plugin version: ClientDetector version 2.4.8

**Describe the bug**
```
[12:52:48 ERROR]: Could not pass event PlayerQuitEvent to ClientDetector v2.4.8
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "org.bukkit.event.player.PlayerQuitEvent.getQuitMessage()" is null
	at de.sportkanone123.clientdetector.spigot.listener.PlayerListener.onQuit(PlayerListener.java:94) ~[ClientDetector.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.heretere.hpwp.listener.HPWPRegisteredListener.callEvent(HPWPRegisteredListener.java:54) ~[HPWP.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:617) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2009) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1989) ~[?:?]
	at xuan.cat.fartherviewdistance.code.branch.v18.Branch_18_ProxyPlayerConnection.a(Branch_18_ProxyPlayerConnection.java:334) ~[FartherViewDistance-9.1.2.jar:?]
	at com.denizenscript.denizen.nms.v1_18.impl.network.handlers.AbstractListenerPlayInImpl.a(AbstractListenerPlayInImpl.java:107) ~[Denizen-1.2.4-b6154-DEV.jar:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:753) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-250]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
Player got kicket for AFK. Sometimes this also happens on normal quit.

**Comment by Sportkanone123** [comment]
Hi, fixed: https://github.com/Sportkanone123/ClientDetector/commit/2eed8ade43ac158397f1e2a392ae06b07e214241
~Sportkanone123
