### ISSUE TITLE
An error occurred when the player joined, the plugin did not work

### ISSUE THREAD

**Issue by misss520** [Sportkanone123/ClientDetector#16]
It gave me a long list of errors, but it didn't work
When loading, it gave an error, I ignored it, I thought, it would work fine, but it just gave me a bunch of errors

Below is the detailed log
Note: The server version I use is 1.8.8, and the ProtocolLib.jar is the latest

PacketEvents caught an unhandled exception while calling your listener.
>java.lang.NullPointerException: null
at de.sportkanone123.clientdetector.spigot.client.processor.PacketProcessor.handlePacket(PacketProcessor.java:35) ~[ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packet.processor.PacketProcessor.handlePacket(PacketProcessor.java:39) ~[ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.listener.NetworkListener.onPacketPlayReceive(NetworkListener.java:37) ~[ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.event.SimplePacketListenerAbstract.onPacketReceive(SimplePacketListenerAbstract.java:45) ~[ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.event.EventManager.callEvent(EventManager.java:51) [ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) [ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) [ClientDetector.jar:?]
at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) [ClientDetector.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_333]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_333]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_333]
at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75) [ViaVersion-4.4.0-1.19.1-pre3-SNAPSHOT.jar:?]
at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59) [ViaVersion-4.4.0-1.19.1-pre3-SNAPSHOT.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]

**Comment by misss520** [comment]
This is an error when loading the plugin

[08:12:14 WARN]: java.lang.IllegalStateException: PacketEvents failed to add a decoder to the netty pipeline. Pipeline handlers: [DefaultChannelPipeline$TailContext#0]
[08:12:14 WARN]:  at de.sportkanone123.clientdetector.spigot.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:101)
[08:12:14 WARN]:  at de.sportkanone123.clientdetector.spigot.packetevents.injector.SpigotChannelInjector.inject(SpigotChannelInjector.java:117)
[08:12:14 WARN]:  at de.sportkanone123.clientdetector.spigot.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:111)
[08:12:14 WARN]:  at de.sportkanone123.clientdetector.spigot.ClientDetector.onLoad(ClientDetector.java:68)
[08:12:14 WARN]:  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[08:12:14 WARN]:  at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[08:12:14 WARN]:  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[08:12:14 WARN]:  at java.lang.Thread.run(Thread.java:750)
[08:12:14 WARN]: Caused by: java.util.NoSuchElementException: splitter
[08:12:14 WARN]:  at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
[08:12:14 WARN]:  at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:188)
[08:12:14 WARN]:  at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:181)
[08:12:14 WARN]:  at de.sportkanone123.clientdetector.spigot.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:98)
[08:12:14 WARN]:  ... 7 more

**Comment by Sportkanone123** [comment]
Will check. Seems to be an issue with PacketsEvents.
~Sportkanone123

**Comment by Sportkanone123** [comment]
> It gave me a long list of errors, but it didn't work When loading, it gave an error, I ignored it, I thought, it would work fine, but it just gave me a bunch of errors
> 
> Below is the detailed log Note: The server version I use is 1.8.8, and the ProtocolLib.jar is the latest
> 
> PacketEvents caught an unhandled exception while calling your listener.
> 
> > java.lang.NullPointerException: null
> > at de.sportkanone123.clientdetector.spigot.client.processor.PacketProcessor.handlePacket(PacketProcessor.java:35) ~[ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packet.processor.PacketProcessor.handlePacket(PacketProcessor.java:39) ~[ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.listener.NetworkListener.onPacketPlayReceive(NetworkListener.java:37) ~[ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.event.SimplePacketListenerAbstract.onPacketReceive(SimplePacketListenerAbstract.java:45) ~[ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.event.EventManager.callEvent(EventManager.java:51) [ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) [ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) [ClientDetector.jar:?]
> > at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) [ClientDetector.jar:?]
> > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
> > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_333]
> > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_333]
> > at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_333]
> > at com.viaversion.viaversion.util.PipelineUtil.callDecode(PipelineUtil.java:75) [ViaVersion-4.4.0-1.19.1-pre3-SNAPSHOT.jar:?]
> > at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:59) [ViaVersion-4.4.0-1.19.1-pre3-SNAPSHOT.jar:?]
> > at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
> > at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]

Should be fixed with commit https://github.com/Sportkanone123/ClientDetector/commit/3995cc385a1bddb897959fe7bf9c35e9edbcb791.
~Sportkanone123

**Comment by Sportkanone123** [comment]
> This is an error when loading the plugin
> 
> [08:12:14 WARN]: java.lang.IllegalStateException: PacketEvents failed to add a decoder to the netty pipeline. Pipeline handlers: [DefaultChannelPipeline$TailContext#0] [08:12:14 WARN]: at de.sportkanone123.clientdetector.spigot.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:101) [08:12:14 WARN]: at de.sportkanone123.clientdetector.spigot.packetevents.injector.SpigotChannelInjector.inject(SpigotChannelInjector.java:117) [08:12:14 WARN]: at de.sportkanone123.clientdetector.spigot.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:111) [08:12:14 WARN]: at de.sportkanone123.clientdetector.spigot.ClientDetector.onLoad(ClientDetector.java:68) [08:12:14 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [08:12:14 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [08:12:14 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [08:12:14 WARN]: at java.lang.Thread.run(Thread.java:750) [08:12:14 WARN]: Caused by: java.util.NoSuchElementException: splitter [08:12:14 WARN]: at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) [08:12:14 WARN]: at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:188) [08:12:14 WARN]: at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:181) [08:12:14 WARN]: at de.sportkanone123.clientdetector.spigot.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:98) [08:12:14 WARN]: ... 7 more

How often does this error occur?
