### ISSUE TITLE
start up error

### ISSUE THREAD

**Issue by jaylac2000** [Sportkanone123/ClientDetector#2]
latest version start  up error

[12:49:14 WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
[12:49:14 WARN]:  in 'string', line 57, column 7:
[12:49:14 WARN]:           - " "
[12:49:14 WARN]:           ^
[12:49:14 WARN]: expected <block end>, but found '?'
[12:49:14 WARN]:  in 'string', line 71, column 7:
[12:49:14 WARN]:           success: "%prefix% &aYou have su ... 
[12:49:14 WARN]:           ^
[12:49:14 WARN]: 
[12:49:14 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[12:49:14 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[12:49:14 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[12:49:14 WARN]:        at de.sportkanone123.clientdetector.spigot.manager.ConfigManager.loadConfig(ConfigManager.java:53)
[12:49:14 WARN]:        at de.sportkanone123.clientdetector.spigot.ClientDetector.onEnable(ClientDetector.java:127)
[12:49:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:49:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:49:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[12:49:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[12:49:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[12:49:14 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[12:49:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[12:49:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:49:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:49:14 WARN]: Caused by: while parsing a block collection
[12:49:14 WARN]:  in 'string', line 57, column 7:
[12:49:14 WARN]:           - " "
[12:49:14 WARN]:           ^
[12:49:14 WARN]: expected <block end>, but found '?'
[12:49:14 WARN]:  in 'string', line 71, column 7:
[12:49:14 WARN]:           success: "%prefix% &aYou have su ... 
[12:49:14 WARN]:           ^
[12:49:14 WARN]: 
[12:49:14 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:514)
[12:49:14 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[12:49:14 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:208)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
[12:49:14 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
[12:49:14 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
[12:49:14 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[12:49:14 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[12:49:14 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[12:49:14 WARN]:        ... 14 more

i deleted old plugin data before re-installing new version

**Comment by Sportkanone123** [comment]
Fixed with 2.0.2, you have to reset your config.yml and message.yml

**Comment by jaylac2000** [comment]
thanks!
