### ISSUE TITLE
Plugin prohibits players from joining on 1.19.1

### ISSUE THREAD

**Issue by Chris6ix** [Sportkanone123/ClientDetector#20]
**General Information**
Server version: Paper 1.19.1 #95
Client version: Fabric 1.19.1
Plugin version: 2.5.1

**Describe the bug**
With the plugin insalled on a 1.19.1 Server, when a player tries to join, this error appears in console and the player gets disconnected:
`[18:02:24] [Netty Server IO #3/WARN]: [de.sportkanone123.clientdetector.spigot.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.ClassCastException: class io.netty.channel.socket.nio.NioSocketChannel cannot be cast to class org.bukkit.entity.Player (io.netty.channel.socket.nio.NioSocketChannel and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @9e89d68)
	at de.sportkanone123.clientdetector.spigot.packetevents.manager.player.PlayerManagerImpl.getChannel(PlayerManagerImpl.java:82) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.manager.player.PlayerManager.sendPacket(PlayerManager.java:45) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.forgemod.newerversion.ForgeHandshake.sendModList(ForgeHandshake.java:28) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.forgemod.newerversion.ForgeHandler.handle(ForgeHandler.java:50) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packet.processor.PacketProcessor.handleLoginPacket(PacketProcessor.java:52) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.listener.NetworkListener.onPacketLoginReceive(NetworkListener.java:42) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.event.SimplePacketListenerAbstract.onPacketReceive(SimplePacketListenerAbstract.java:43) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) ~[ClientDetector.jar:?]
	at de.sportkanone123.clientdetector.spigot.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) ~[ClientDetector.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:122) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:02:24] [Server thread/INFO]: [Redacted] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): PooledUnsafeDirectByteBuf(ridx: 11, widx: 11, cap: 256)`

and the player sees this screen:
![2022-07-31_18 02 37](https://user-images.githubusercontent.com/65610536/182035944-ce549e9d-bde5-4b7d-ae7c-6f07e0e77b3c.png)

Because this problem prohibits players from even joining the server, I have to remove the plugin from my server until this issue is fixed.

**To Reproduce**
Join a 1.19.1 server with ClientDetector installed.

**Comment by Sportkanone123** [comment]
The newest version of ClientDetector now supports 1.19.1 and 1.19.2.
